language: android

android:
  components:
  - tools                             # Tools
  - platform-tools                    # Platform tools
  - build-tools-28.0.3                # Build tools version
  - android-28                        # Target SDK version
  - extra-android-m2repository        # Support repo
  - extra-google-m2repository         # Google repo

jdk:
- oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"

script:
- cp local.properties.ci.properties local.properties
- ./gradlew build

branches:
  only:
  - master

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.gradle
